---
title: Ecology of foam establishment during anaerobic digestion of wastewater sludge
  following process disturbance - Figure 7
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

## Load packages and data

```{r, message=FALSE, warning=FALSE}
options("lubridate.week.start" = 3)
library(tidyverse)
theme_set(theme_bw())  
library(ggpubr)
library(lubridate)
library(ggrepel)
library(phyloseq)
`%notin%` = Negate(`%in%`)
# Prevalence table function
# get overview of abundances, mean prevalence is the mean 'appearance' of ASVs of the taxon across all samples
prevalencedf <- dget("./custom-functions/myprevalencetablefunction.R")
pca_helper <- dget("./custom-functions/pca_helper.R")
startoperation <- ymd("2023-03-01")
cols <- c("#4D98AC", "#985C64", "#ff0000", "purple", "#C4A484")
names(cols) <- c("Control", "Treatment", "Full-scale", "PSTWAS", "Foam")

## LOAD MASTERDATA
# change this path to where you store the .csv file. you can provide an absolute path like this. Check the path syntax for Windows as it might be different. 
masterdata <- read.csv("./data/masterdataProject1C_May24.csv")
masterdata <-  masterdata %>%
  mutate(Date = lubridate::dmy(as.character(Date)) )
# Make AD, Treatment and SludgeType = factors
masterdata$AD <- factor(masterdata$AD, levels = c("AD1", "AD2","AD3", "AD4","AD5", "AD6", "Full-scale", "PSTWAS"))
masterdata$SludgeType <- factor(masterdata$SludgeType, levels = c("Control", "Treatment", "Foam", "Full-scale", "PSTWAS"))
masterdata$Treatment <- factor(masterdata$Treatment, levels = c("Control", "Treatment", "Full-scale", "PSTWAS"))
masterdata$Period <- factor(masterdata$Period, levels = c("Converging", "SteadyState", "Glycerol", "Inhibition", "Recovery/Feedingpause", "Recovery/Foaming", "Recovery/Postfoam", "SteadyState/Postfoam"))
masterdata <- masterdata %>% 
mutate(across(Observed:pielou_ev, ~as.numeric(.)))

## METADATA SUBSET FOR PHLOSEQ
# merge individual samples into the pooled samples - mean values
df <- masterdata %>% 
   as_tibble() %>% dplyr::filter(SampleID.CHN %in% c("S567_AD1", "S568_AD2", "S569_AD3","S570_AD4","S571_AD5","S572_AD6"
                                                     )) %>% column_to_rownames("SampleID.CHN") 
df <- data.frame(df %>% group_by(Date, Period ) %>% summarise_each(funs(mean)))
rownames(df) <- c("S567toS572_AD1.6")
df$AD <- c("AD1.2.3.4.5.6")
df$Treatment <- c("Control")

# not pooled samples 
df2 <- masterdata %>% 
   as_tibble() %>% dplyr::filter(SampleID.CHN %in% c( "S371_Adfull", "S1007_AD1", "S1008_AD2","S1009_AD3", "S1010_AD4",
                                                      "S1011_AD5","S1012_AD6",
                                                     "S1201_AD1","S1202_AD2", "S1203_AD3", "S1204_AD4", "S1205_AD5", 
                                                     "S1275_ADFull", "S1556_ADFull", 
                                                     "S1815_ADFull","S1183_AD1","S1183_AD2","S1185_AD3", "S1186_AD4", 
                                                     "S1187_AD5", "S1188_AD6"
                                                     ) & 
                                   SludgeType != c("Foam")) %>% 
   column_to_rownames("SampleID.CHN")

#combined the dfs
metadata <- rbind(df,df2)
#rownames(metadata)
metadata <- metadata %>% rownames_to_column("ID") %>% 
  mutate("SampleID" = ID) %>% column_to_rownames("ID")  %>% 
  mutate("SampleID" = factor(SampleID, levels = c("S567toS572_AD1.6", "S1007_AD1", "S1008_AD2","S1009_AD3", "S1010_AD4", "S1011_AD5","S1012_AD6",
                                                  "S1201_AD1","S1202_AD2", "S1203_AD3", "S1204_AD4", "S1205_AD5",
                                                  "S1183_AD1","S1183_AD2","S1185_AD3", "S1186_AD4", "S1187_AD5", "S1188_AD6",
                                                  "S371_full", "S1275_ADFull", "S1556_ADFull", "S1815_ADFull"
                                                     )))
metadata$SampleType <- c("Steady State", "Full-scale", "Control1", "Treatment1", "Control2","Control3","Treatment2","Treatment3",
  "Control1", "Treatment1", "Control2","Control3","Treatment2","Treatment3",
  "Control1", "Treatment1", "Control2","Control3","Treatment2","Full-scale", "Full-scale", "Full-scale")
metadata <- metadata %>% mutate(VFAs = rowSums(select(., contains("acid"))) )

## Add pH values to the 15h May (from 14th May)
metadata[c(3,4,5,6,7,8),"pH"] <- c(7.26, 5.87, 7.36, 7.31, 5.89, 5.59) # copied from the masterdata 14th May
metadata[c(9,10,11,12,13,14),"pH"] <- c(7.53, 7.27, 7.45, 7.47, 7.05, 6.79) # copied from the masterdate 31st May

#VFAs from 29th May = add to data from 02 June for figure only
metadata[c('S1183_AD1','S1183_AD2','S1185_AD3', 'S1186_AD4','S1187_AD5',  'S1188_AD6'),]$VFAs <- c(40.01, 2397.80, 53.71, 36.32, 5037.26, 5134.20)

vars <- c("Date", "SampleType")
metadata <- tidyr::unite(metadata, "Sample", all_of(vars),remove = FALSE )

metadata$CSTR <- str_replace_all(metadata$AD, c("AD1"="C1", 
                                      "AD2"="T1", 
                                          "AD3"="C2", 
                                            "AD4"="C3", 
                                              "AD5"="T2", 
                                               "AD6"="T3",
                                                "Full-scale" = "Full-scale",
                                       "AD1.2.3.4.5.6" = "CSTRs") )
vars <- c("CSTR", "Treatment")
metadata <- tidyr::unite(metadata, "CSTR_Treat", all_of(vars),remove = FALSE )
rm(df, df1, df2)

## TAXA / METABOLITES PS OBJECT
# create a metabolome ps object for easy data handling and transformations
taxa <-  data.frame(read.csv("./data/020604-metabolimicstaxatable.csv")) %>% column_to_rownames("Sample.ID")
taxa <-  data.frame(t(taxa))
taxa <-  data.frame(t(taxa))

## ABUNDANCES OF METABOLITES FOR PS OBJECT
metabolome <- data.frame(read.csv("./data/020524-metabolimicsresults_responseChris.csv")) 
# remove first three rows
metabolome <- metabolome[c(4:nrow(metabolome)),] 
metabolome <- metabolome %>% remove_rownames %>% column_to_rownames("Samples")
metabolome <- data.frame(t(metabolome)) %>% 
  rownames_to_column("ID")
metabolome$ID <- str_replace_all(metabolome$ID, c("X48.53"="S567toS572_AD1.6", "X35"="S371_full",    "X92"="S1007_AD1",    "X93"="S1008_AD2",    "X94"="S1009_AD3",   "X95"="S1010_AD4",    "X96"="S1011_AD5" ,   "X97"="S1012_AD6",    "X101"="S1201_AD1",   "X102"="S1202_AD2",  "X103"= "S1203_AD3" , "X104.2"="S1204_AD4", "X105"="S1205_AD5",  "X107"= "S1275_ADFull",   "X142"="S1556_ADFull",  "X162"="S1815_ADFull",  "X169"= "S1183_AD1",   "X170"="S1183_AD2" ,  "X171"="S1185_AD3",  "X172"="S1186_AD4",   "X173"="S1187_AD5" ,  "X174"="S1188_AD6"))
metabolome <- metabolome %>% column_to_rownames("ID")
# rownames(metabolome) <- rnames   # in case for later
metabolome <- metabolome %>% mutate_if(is.character, as.numeric)
metabolome <- data.frame(t(metabolome))
# Create the phyloseq object 
psmv <-phyloseq(
  otu_table(metabolome, taxa_are_rows = T), 
  sample_data(metadata),
  tax_table(as.matrix(taxa))
)
sample_data(psmv)$Treatment <-  factor(sample_data(psmv)$Treatment, levels = c("Control", "Treatment", "Full-scale", "PSTWAS"))


## LOG ABUNDANCES OF METABOLITES FOR PS OBJECT
 metabolome <- data.frame(read.csv("./data/020524-metabolimicsresults_LOGresponseChris.csv")) 
#LOG - FULL DATA
#metabolome <- data.frame(read.csv("/Users/christiankrohn/Library/CloudStorage/OneDrive-RMITUniversity/Documents/Project1C_files/Experiment_LongTermMonitoring/Data/Rdata/020524-metabolimicsresults_LOGresponseFULLChris.csv")) 
# remove first three rows
metabolome <- metabolome[c(4:nrow(metabolome)),] 
metabolome <- metabolome %>% remove_rownames %>% column_to_rownames("Samples")
metabolome <- data.frame(t(metabolome)) %>% 
  rownames_to_column("ID")
metabolome$ID
metabolome$ID <- str_replace_all(metabolome$ID, c("X48.53"="S567toS572_AD1.6", "X35"="S371_full",    "X92"="S1007_AD1",    "X93"="S1008_AD2",    "X94"="S1009_AD3",   "X95"="S1010_AD4",    "X96"="S1011_AD5" ,   "X97"="S1012_AD6",    "X101"="S1201_AD1",   "X102"="S1202_AD2",  "X103"= "S1203_AD3" , "X104.2"="S1204_AD4", "X105"="S1205_AD5",  "X107"= "S1275_ADFull",   "X142"="S1556_ADFull",  "X162"="S1815_ADFull",  "X169"= "S1183_AD1",   "X170"="S1183_AD2" ,  "X171"="S1185_AD3",  "X172"="S1186_AD4",   "X173"="S1187_AD5" ,  "X174"="S1188_AD6"))
metabolome <- metabolome %>% column_to_rownames("ID")
# rownames(metabolome) <- rnames   # in case for later
metabolome <- metabolome %>% mutate_if(is.character, as.numeric)
metabolome <- data.frame(t(metabolome))

# Create the phyloseq object 
psml <-phyloseq(
  otu_table(metabolome, taxa_are_rows = T), 
  sample_data(metadata),
  tax_table(as.matrix(taxa))
)
sample_data(psml)$Treatment <-  factor(sample_data(psml)$Treatment, levels = c("Control", "Treatment", "Full-scale", "PSTWAS"))

psmv
psml
psmlf <- psml
```


## Figure 7 
### Complex heatmap
```{r}
library(circlize)
library(ComplexHeatmap)
# Filter out full-scale AD
ps.tmp <- prune_samples(sample_data(psml)$AD != c("Full-scale"), psml)
ps.tmp <- prune_samples(sample_data(ps.tmp)$AD %notin% c("AD1.2.3.4.5.6"), ps.tmp)
ps.tmp <- phyloseq::subset_taxa(ps.tmp, CompoundName %notin% c("23-1949_Pentadecanoic acid, n- [1TMS] COPY", 
                                                               "29-2038.3_(910; 9-(Z)-Hexadecanoic acid [1TMS]",
                                                               "58-1775.1_Glycerol-3-phosphate, DL- [4TMS]", 
                                                               "26-2267_Permethyl-oligosiloxane"))
sample_data(ps.tmp)$CSTR <- str_replace_all(sample_data(ps.tmp)$AD, c("AD1"="C1", 
                                       "AD2"="T1", 
                                          "AD3"="C2", 
                                            "AD4"="C3", 
                                              "AD5"="T2", 
                                               "AD6"="T3",
                                                "AD_full" = "Full-scale") )

col_fun = colorRamp2(c(min(otu_table(ps.tmp)), mean(otu_table(ps.tmp)), max(otu_table(ps.tmp))), c("black", "steelblue", "#FCFDBFFF"))
taxtable <- data.frame(tax_table(ps.tmp))
set.seed(1232145)
colAnn <- HeatmapAnnotation(
        Date = as.character(sample_data(ps.tmp)$Date),
        col = list(Date = c("2023-04-26" = "#ABB065", "2023-05-01" = "#D2A277","2023-05-15" = "#E495A5", 
                             "2023-06-02" = "#72BB83", "2023-06-05" = "#39BEB1", "2023-06-09" = "#64B5D6", 
                             "2023-06-28" = "#D995CF", "2023-08-09" = "#ACA4E2")),
       DNA = anno_barplot(sample_data(ps.tmp)$DNA_mg_gCOD, width = unit(4, "cm")), 
       VFAs = anno_barplot(sample_data(ps.tmp)$VFAs, width = unit(4, "cm"))
                        )
set.seed(1232145)
row_ha = rowAnnotation(`KEGG class` = taxtable$Label)

#cols <- colorspace::rainbow_hcl(length(unique(sample_data(ps.tmp)$Date)))
#row_ano = rowAnnotation(foo = anno_block(gp = gpar(fill = 2:4)))

set.seed(1232145)
 fig <- Heatmap((otu_table(ps.tmp)), 
        name = "Abundances", #title of legend
        row_names_gp = gpar(fontsize = 6.5),
        #split = sample_data(ps.tmp)$Treatment,
        col_fun,
        show_column_names = TRUE,
         show_row_names = TRUE,
       row_labels = c(data.frame(tax_table(ps.tmp))$CompoundName2),
       column_labels = c(data.frame(sample_data(ps.tmp))$CSTR),
       column_names_gp = gpar(fontsize = 10),
       clustering_method_columns = "ward.D",
       top_annotation = colAnn,
       left_annotation = row_ha,
    row_km = 4
       )    
       #column_split = 4
        # Text size for row names
 fig
 
 png("./Figures/heatmap_metabolites.png", width = 17, height = 22,pointsize = 12,units="cm",res=300)
draw(fig, padding = unit(c(3, 3, 2, 2), "mm"), merge_legend = TRUE) ## see right heatmap in following
dev.off()

```

### Barplot omu
```{r}
library(omu)
#https://cran.r-project.org/web/packages/omu/vignettes/Omu_vignette.html#Introduction_to_omu

ps.tmp <- prune_samples(sample_data(psml)$Treatment %in% c("Control","Treatment"), psml)
ps.tmp <- prune_samples(sample_data(ps.tmp)$AD %notin% c("AD1.2.3.4.5.6"), ps.tmp)
ps.tmp <- phyloseq::subset_taxa(ps.tmp, CompoundName %notin% c("23-1949_Pentadecanoic acid, n- [1TMS] COPY", 
                                                               "29-2038.3_(910; 9-(Z)-Hexadecanoic acid [1TMS]",
                                                               "58-1775.1_Glycerol-3-phosphate, DL- [4TMS]"))
counts <- data.frame(otu_table(ps.tmp)) 
counts$Metabolite <- data.frame(tax_table(ps.tmp))$CompoundName2
counts$KEGG <- data.frame(tax_table(ps.tmp))$KEGG
counts$Class <- data.frame(tax_table(ps.tmp))$Label  # based on a mix of KEGG parent and subclasses as per Dan's advice
counts$Class2 <- data.frame(tax_table(ps.tmp))$Subclass_1
counts <- counts %>% dplyr::select(Metabolite, KEGG, Class, Class2, S1007_AD1:S1188_AD6)
# 9Z hexadeacanoic acid 
# DL-Glycerol-3-phosphate
# n-Pentadecanoic acid
# were aggregated - summed - which is not technically correct. 
meta.tmp <- data.frame(sample_data(ps.tmp)) %>% 
  rename(Date_type = "Sample") %>% 
           rename(ID = "AD") %>% 
  rownames_to_column("Sample") %>% 
  dplyr::select(Sample, ID, Treatment)

DF_stats <- omu_summary(count_data = counts, 
                        metadata = meta.tmp, numerator = "Control", 
                        denominator = "Treatment", response_variable = "Metabolite", 
                        Factor = "Treatment", log_transform = FALSE, p_adjust = "BH", 
                        test_type = "welch", paired = FALSE)

# paired test does not work. Maybe because of uneven number of replicates (i.e. 2 and 3 per digester)
#Error in t.test.default(x = respVar[, 1L], y = respVar[, 2L], paired = TRUE,  : 
 # not enough 'x' observations

DF_anova <- omu_anova(count_data = counts, metadata = meta.tmp, response_variable = "Metabolite", model = ~ Treatment)

# Gathering Functional Orthology and Gene Data
#DF_stats_sub <- subset(DF_stats, Class=="Organic acids")
# DF_stats_sub <- DF_stats[which(DF_stats[,"padj"] <= 0.05),]
# DF_stats_sub_KO <- KEGG_gather(DF_stats_sub)
# To explore more 

## barplot 
DF_stats_counts <- data.frame(DF_stats) %>% 
  dplyr::filter(padj <= 0.05) %>% 
  dplyr::mutate('Label' = if_else(log2FoldChange > 0, "Increase", "Decrease"))
DF_stats_counts$Label[28] <- "Increase" 
DF_stats_counts <- DF_stats_counts %>% group_by(Class, Label) %>%
   summarise(n= n()) %>% 
  mutate('Significant_changes' = if_else(Label %in% c("Decrease"), n*-1, n*1)) %>% 
 arrange(desc(n))
DF_stats_counts$Class <- factor(DF_stats_counts$Class, levels = c(DF_stats_counts$Class %>% unique()))
DF_stats_counts$Label <- factor(DF_stats_counts$Label, levels = c("Increase","Decrease"))

p1 <- ggplot(DF_stats_counts, aes(fill=Label, y=Significant_changes, x=Class)) + 
  geom_bar(position="stack", stat="identity", colour = "black") +
   theme_classic() +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.8,0.8),
    axis.text.y = element_text(size = 10),
    axis.title.y = element_text(size = 8.5),
    axis.text.x = element_text(angle = 65,  hjust=1, size = 7.5)
  ) +
  scale_fill_manual(values = c("firebrick2","dodgerblue2" )) +
  ylab("Number of significant changes")
  
p1
ggsave(plot = p1, "./Figures/barplot_metabolites.png", height=7.5, width=6, units='cm', dpi=300)
```

